### ISSUE TITLE
bits package

### ISSUE THREAD

**Issue by sudachen** [spacemeshos/fixed#1]
https://github.com/spacemeshos/fixed/blob/09eab1cf72806500628335adbb315375f3eb2a0e/52_12/fixed.go#L73

Why do not use bits.Mul64 (and bits.Div64 for Div)? Something like:

```go
	hi,lo := bits.Mul64(uint64(x),uint64(y))
	return Fixed(hi<<(64-fracBits) | lo>>fracBits)
```

```go
	lo := uint64(x << fracBits)
	hi := uint64(x >> (64-fracBits)) // with sign
	ret,_ := bits.Div64(l,h,uint64(y))
```

https://github.com/spacemeshos/fixed/blob/09eab1cf72806500628335adbb315375f3eb2a0e/26_6/fixed.go#L73

Why do not mul/div it as expanded with a sign to int64?

**Comment by noamnelke** [comment]
This is very similar to the previous implementation and it's considerably slower than my implementation.

This was the original implementation:
https://github.com/spacemeshos/fixed/blob/0ae502cec0babfd7cfc6170d94beab337288bf2c/fixed.go#L103-L134

In my benchmark I get, for the original implementation:
```
BenchmarkFixed_Mul-8   	300000000	         4.99 ns/op
```
and for my implementation:
```
BenchmarkFixed_Mul-8   	2000000000	         0.28 ns/op
```
So an order of magnitude faster.

I believe this is because the original implementation has to work hard to calculate bits that end up being shifted away and lost, while my implementation does less of this unnecessary work.

I haven't tried your version of `Div()` but is there any reason to believe it won't suffer from the same issue?

**Comment by sudachen** [comment]
Hm, I'll check, but as far as I know, bits.Mult64 has to be intrinsic. May be I'm wrong.

**Comment by noamnelke** [comment]
You mean that it's built-in? Yes, from Go 1.12, but it's the same implementation:

https://github.com/golang/go/blob/96e83664378918980bd8f60822c4bc39befcb668/src/math/bits/bits.go#L459-L478

**Comment by sudachen** [comment]
An intrinsic function is Go code written in regular Go. These functions are known the the Go compiler which contains replacements which it can substitute during compilation.

https://dave.cheney.net/2019/08/20/go-compiler-intrinsics

**Comment by sudachen** [comment]
Anyway I'll test how/if compiler substitutes better implementation here

**Comment by noamnelke** [comment]
aha, interesting. The original implementation didn't use `math/bits` but a similar implementation (with `int64` instead of `uint64`). Maybe it's worth checking if using the intrinsic functions from `math/bits` improves performance.

**Comment by sudachen** [comment]
![image](https://user-images.githubusercontent.com/1428/86219535-58370500-bb50-11ea-90c6-cd69f5cc320a.png)

**Comment by sudachen** [comment]
But something wrong here, it must be faster.

**Comment by noamnelke** [comment]
Nice, however, while it will offset most of the difference, it looks like my implementation will still be faster based on the previous benchmarks I sent.

I'll give it a try, but it means I need to upgrade Go (I'm still on Go 1.11 which doesn't have these functions).

**Comment by sudachen** [comment]
By the way, the Current version is 1.14 ;-)

**Comment by sudachen** [comment]
It looks like
![image](https://user-images.githubusercontent.com/1428/86220895-376faf00-bb52-11ea-8023-51d8dbee7554.png)

**Comment by sudachen** [comment]
In other words, bits.Mul64 practically is a single CPU command - MULQ.

**Comment by noamnelke** [comment]
Very interesting!

I upgraded Go to 1.14.4 and tried your implementation vs. mine again. Mine gave `0.279 ns/op` while yours gave `0.293 ns/op` which is indistinguishable! Running both several times gives about 0.01 difference which I don't think is statistically significant.

To make yours work I'd need to fix rounding and ensure it properly handles negative numbers. Those could possibly slow it down a little.

Two advantages of your method: (1) My method doesn't support more than half the bits used for the fraction, yours doesn't have this limitation; (2) You method is more "conventional".

I'll work on it some more later today. Thanks for this!!

**Comment by noamnelke** [comment]
This is the best I was able to implement `Mul()` using `bits.Mul64()`:

```go
func (x Fixed) Mul(y Fixed) Fixed {
	xs := x >> (totalBits - 1)                                 // x >= 0 ? 0 : -1
	ys := y >> (totalBits - 1)                                 // y >= 0 ? 0 : -1
	sign := 1 + 2*(xs^ys)                                      // x*y >= 0 ? 1 : -1
	hi, lo := bits.Mul64(uint64((x^xs)-xs), uint64((y^ys)-ys)) // abs(x): (x^xs)-xs
	rounding := (lo >> (fracBits - 1)) & 1
	return sign * Fixed(hi<<(totalBits-fracBits)|lo>>fracBits+rounding)
}
```

This specific line: `sign := 1 + 2*(xs^ys)` is causing this implementaion to be an order of magnitude slower than my implementation. It was originally more simple/readable, but I got to this point trying to optimize, without success (this is the fastest version I was able to produce).

An additional problem with this implementation that I can't seem to fix is that there's a specific test case that seems to break due to wrong rounding of a negative number (you're welcome to try it). It works for all other test cases (including many cases where we round a negative number).

I may be missing something basic - if you see it, please let me know, otherwise I'm abandoning this effort and staying with the current implementation.
